/**
 * Golden Master tests: compare TypeScript SVG output against Java reference SVGs.
 *
 * The expected SVGs are generated by the Java BatchRenderer (ant batch-render)
 * and committed to tests/golden/expected/. This test renders each example from
 * TypeScript and compares the output structurally (path count, coordinates with
 * tolerance, colors, strokes).
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, readdirSync, existsSync, statSync } from 'fs';
import { join, relative } from 'path';
import { parseNdbx, clearLibraryCache } from '../../src/ndbx/parser';
import { evaluate } from '../../src/eval/evaluate';
import { exportSvg } from '../../src/svg/export';
import { TestPlatform } from '../../src/platform';
import { loadFont } from '../../src/ops/text';
import type { NodeLibrary } from '../../src/node/library';
import { compareSvg } from './compare-svg';

const ROOT = join(__dirname, '..', '..', '..', '..');
const EXAMPLES_DIR = join(ROOT, 'examples');
const EXPECTED_DIR = join(__dirname, 'expected');
const FONT_DIR = join(__dirname, '..', '..', 'fonts');

/** Patterns to skip — examples depend on external resources, hardware, or unimplemented ops. */
const SKIP_PATTERNS = [
  'device/',              // hardware-dependent (audio, mouse, OSC)
  'Web/',                 // network-dependent (httpGet)
  'Geocoding/',           // network-dependent (queryJSON)
  'Twitter',              // network-dependent
  '09 Binary',            // compound/boolean ops (needs computational geometry lib)
  '13 Tilling',           // depends on compound ops
];

function shouldSkip(relPath: string): boolean {
  return SKIP_PATTERNS.some((p) => relPath.includes(p));
}

function loadLibraries() {
  const libs: Record<string, NodeLibrary> = {};
  for (const name of ['core', 'corevector', 'list', 'math', 'color', 'string', 'data', 'network']) {
    try {
      libs[name] = parseNdbx(readFileSync(join(ROOT, `libraries/${name}/${name}.ndbx`), 'utf-8'));
    } catch { /* some libs may not exist */ }
  }
  return (name: string) => libs[name];
}

/** Recursively find all .ndbx files. */
function findNdbxFiles(dir: string): string[] {
  const results: string[] = [];
  if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...findNdbxFiles(full));
    } else if (entry.endsWith('.ndbx')) {
      results.push(full);
    }
  }
  return results;
}

describe('Golden Master: Java vs TypeScript SVG output', () => {
  const loader = loadLibraries();
  const ndbxFiles = findNdbxFiles(EXAMPLES_DIR);

  // Load Inter.ttf for ALL font names used in examples.
  // Java golden masters remap all fonts to Inter for reproducibility.
  const platform = new TestPlatform();
  const interFontPath = join(FONT_DIR, 'Inter.ttf');
  const FONT_NAMES = ['Verdana', 'Verdana-Bold', 'Arial-Black', 'HelveticaNeue-Bold'];
  if (existsSync(interFontPath)) {
    const fontBytes = new Uint8Array(readFileSync(interFontPath));
    for (const name of FONT_NAMES) {
      platform.addFont(name, fontBytes);
    }
    beforeAll(async () => {
      for (const name of FONT_NAMES) {
        await loadFont(fontBytes, name);
      }
    });
  }

  for (const ndbxPath of ndbxFiles) {
    const relPath = relative(EXAMPLES_DIR, ndbxPath);
    const svgRelPath = relPath.replace(/\.ndbx$/, '.svg');
    const expectedPath = join(EXPECTED_DIR, svgRelPath);

    if (shouldSkip(relPath)) {
      it.skip(`${relPath} (skipped: external dependency)`, () => {});
      continue;
    }

    if (!existsSync(expectedPath)) {
      it.skip(`${relPath} (no golden SVG)`, () => {});
      continue;
    }

    it(`matches golden: ${relPath}`, async () => {
      clearLibraryCache();

      const xml = readFileSync(ndbxPath, 'utf-8');
      const lib = parseNdbx(xml, loader);

      if (!lib.root.renderedChild) {
        // No rendered child — nothing to compare
        return;
      }

      const result = await evaluate({
        library: lib,
        frame: 1,
        platform,
      });

      const width = parseFloat(lib.properties.canvasWidth ?? '1000');
      const height = parseFloat(lib.properties.canvasHeight ?? '1000');

      const actualSvg = exportSvg(result.paths, result.texts, { width, height });
      const expectedSvg = readFileSync(expectedPath, 'utf-8');

      const diff = compareSvg(actualSvg, expectedSvg, 1.0);

      if (!diff.match) {
        const summary = diff.differences.slice(0, 10).join('\n  ');
        const more = diff.differences.length > 10 ? `\n  ... and ${diff.differences.length - 10} more` : '';
        expect.fail(`SVG mismatch for ${relPath}:\n  ${summary}${more}`);
      }
    });
  }
});
